ingress:
  - hostname: api.rodolfocordones.com
    service: http://api:4000
  - hostname: docker.rodolfocordones.com
    service: http://portainer:9000
  - service: http_status:404

# Servicio TCP para Postgres dentro del t√∫nel
services:
  postgres:
    url: tcp://postgres:5432
    hostname: db.rodolfocordones.com